New feature: Allows the output data of a layer to remain in the low-level memory for later use when possible
KULeuven-MICAS/zigzag pull request #25
Opened 2023-10-05 13:15 UTC by JiacongSun

### **New feature:**

- This feature allows the output data of a layer to remain in the low-level memory when possible. This enables direct use of the output data by the next layer, eliminating the need for data to travel to/from the top memory level.

**Note:** 
1. This feature applies only to layers on the same branch.
2. By default, it is assumed that the initial input and final output of the entire network can be generated from the low-level memory. If your case requires them to travel to/from the top memory level, you can change this assumption by setting the `workload_data_always_from_top_mem` parameter to `True` in the `run()` function within the `SearchNoUseMemStage.py` file.

### **New stages:**
- SearchNoUseMemStage: This stage searches for unnecessary top memory levels for each layer and generates a pointer indicating which level the output data of each layer should travel up to.
- RemoveNoUseMemStage: This stage removes memory instances with a level higher than the pointer.

### **How to use:**
- Place the **SearchNoUseMemStage** before the **WorkloadStage**, and place the **RemoveNoUseMemStage** after the **WorkloadStage**.

### **Example:**
An example function, `get_hardware_performance_zigzag_unused_mem_removing` is provided in `api.py` for reference.

2023-10-09 16:37 UTC, asyms requested changes
Please take a look at the comments, and format your code using [black](https://pypi.org/project/black/)

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +class RemoveNoUseMemStage(Stage):
This name is not the most informative. Maybe something like "RemoveUnusedMemoryStage"?

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +    def generate_accelerator_removing_nouse_mem(self):
Similarly rename this function.

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +            act_operand = self.layer.memory_operand_links[[operand for operand in self.layer.input_operands if operand not in self.layer.constant_operands][0]]  # act representation
Rename all operand variables to reflect if they're "layer operands" or "memory operands" either in the name or in comments

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/SearchNoUseMemStage.py
> +class SearchNoUseMemStage(Stage):
Rename this class and documentation to "SearchUnusedMemoryStage" or something similar.

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +        for pos, ele in enumerate(self.mem_update_list[f"{curr_id}"]):
is curr_id not already a string? If not, you should convert a variable to a string using str(...)

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +                target_act_mem_level = self.mem_update_list[f"{curr_id}"][pos][f"{act_operand}"]
Pretty sure act_operand is already a string?

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/RemoveNoUseMemStage.py
> +                "Scale your core-defined dataflows accordingly here."
Why do the dataflows have to be scaled?

2023-10-09 16:37 UTC, asyms commented on zigzag/classes/stages/SearchNoUseMemStage.py
> +        param const_operand: constant operand name (e.g. "W")
You specify three parameters but the function has no parameters?

2023-10-21 08:14 UTC, JiacongSun commented
**New fixes:**

1. SearchNoUseMemStage is renamed as SearchUnusedMemoryStage, RemoveNoUseMemStage is renamed as RemoveUnusedMemoryStage.
2. Coding style in stages above are reformated using black.
3. Add more comments in the new stages, including explicitly label whether a operand is of the layer representation or the mem representation.
4. pytest cases are added under `/tests/main/test_without_unused_memory/`. Original pytest cases are moved to `/tests/main/test_origin/`.

**Extra note:**

- Only when user-defined workload (.py) is used **and** there are Adder layers within the workload, the estimation of SearchUnusedMemoryStage for these Adder layers is more pessimistic, which means the topest memory level for output of these Adder layers possibly is higher than expected. (For details, please refer to the comments in SearchUnusedMemoryStage).
- For other cases (.onnx workload or non-Adder layers), there is no problem.

2023-10-23 09:27 UTC, asyms approved these changes
Looks good to me!

2023-10-23 09:48 UTC, merged