feat: ordering of only relevant loops(no visual)
KULeuven-MICAS/zigzag pull request #41
Opened 2023-12-22 10:47 UTC by Moyne

Additional parameter that can be received on a layer that defines a set of loop to be left unordered
Blocking loop factorization and ordering of such loops
(no update to the visual bar yet)

2024-02-01 21:22 UTC, asyms reviewed
One small question regarding the unordered loops. Are they placed as the start (innermost) or end (outermost) loop?

2024-02-01 21:22 UTC, asyms commented on zigzag/classes/opt/temporal/loma/multipermute.py
> +    return [(name,size) for name,size in original_multiset if name in unordered_loops]+l
Does this not place the "unordered loops" at the start (i.e. innermost loops) of the permutation? As opposed to "at the end" as you state in the PR?

2024-02-06 11:14 UTC, Moyne commented
Hi, thank you for the question, they are placed as the innermost ones (so at the end of the computation, where the tensors should be allocated already at innermost memory level)

2024-02-23 16:03 UTC, asyms requested changes
I'm not entirely sure how you would use this. Can you add some test scenarios that use it in a way in a new folder here: https://github.com/KULeuven-MICAS/zigzag/tree/master/tests/main ?

2024-07-22 17:34 UTC, asyms commented
@moyne Could you please resolve the conflicts? I still believe your additions would add significant value to our project!

2024-09-02 12:32 UTC, moyne commented
Hi @asyms sorry for the late reply, I'll try to fix it maybe even with a new PR that considers the case for output stationary workloads separetely, what do you think about it? Maybe it would be cool to define the type of workload supported and put constraints on the memory allocator/loop factorization knowing these info

2024-09-03 10:04 UTC, asyms commented
Hi @moyne,

There has been more work related to this since this PR was opened. See: https://github.com/KULeuven-MICAS/zigzag/pull/75

It would indeed be great if you can take a look at that PR and the state of the codebase and submit another PR in case there is anything missing functionality-wise.

P.S.: Marian also mentioned you have some systolic array modelling changes, please let us know how we can help to upstream these!

2024-09-03 10:04 UTC, closed without merging